use_frameworks!

target 'JExpandableTableView_Example' do
  pod 'JExpandableTableView', :path => '../'
  pod 'SVProgressHUD', '~> 2.0'

  target 'JExpandableTableView_Tests' do
    inherit! :search_paths

    
  end
end
